services:
  - type: web
    name: dakika
    env: python
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "gunicorn app:app --bind 0.0.0.0:${PORT:-5000} --timeout 120"
    plan: free
